version: '3'
services:
  app:
    build: .
    ports:
      - "9000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
